name: CI
permissions:
  contents: read

on:
  push:
    branches: ['**']

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  check:
    needs: build
    uses: ./.github/workflows/check.yaml

  test-integration:
    needs: [build, check]
    uses: ./.github/workflows/test-integration.yaml
    secrets: inherit

  release:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/canary' || github.ref == 'refs/heads/dx-542-update-to-gha')
    needs: [build, check, test-integration]
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: ./.github/workflows/release.yaml
    secrets:
      VAULT_URL: ${{ secrets.VAULT_URL }}
