name: CI
permissions:
  contents: read

on:
  push:
    branches: ['**']

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  check:
    needs: build
    uses: ./.github/workflows/check.yaml

  test-demo-projects:
    needs: [build, check]
    uses: ./.github/workflows/test-demo-projects.yaml
    secrets: inherit

  test-integration:
    needs: [build, check, test-demo-projects]
    uses: ./.github/workflows/test-integration.yaml
    secrets: inherit

  release:
    if: github.event_name == 'push' && contains(fromJSON('["refs/heads/main", "refs/heads/beta", "refs/heads/canary", "refs/heads/dev"]'), github.ref)
    needs: [build, check, test-demo-projects, test-integration]
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: ./.github/workflows/release.yaml
    secrets:
      VAULT_URL: ${{ secrets.VAULT_URL }}
